// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vconv1__Syms.h"


void Vconv1___024root__traceChgSub0(Vconv1___024root* vlSelf, VerilatedVcd* tracep);

void Vconv1___024root__traceChgTop0(void* voidSelf, VerilatedVcd* tracep) {
    Vconv1___024root* const __restrict vlSelf = static_cast<Vconv1___024root*>(voidSelf);
    Vconv1__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    {
        Vconv1___024root__traceChgSub0((&vlSymsp->TOP), tracep);
    }
}

void Vconv1___024root__traceChgSub0(Vconv1___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vconv1__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    vluint32_t* const oldp = tracep->oldp(vlSymsp->__Vm_baseCode + 1);
    if (false && oldp) {}  // Prevent unused
    // Body
    {
        if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[0U])) {
            tracep->chgSData(oldp+0,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[0]),16);
            tracep->chgSData(oldp+1,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[1]),16);
            tracep->chgSData(oldp+2,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[2]),16);
            tracep->chgSData(oldp+3,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[3]),16);
            tracep->chgSData(oldp+4,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[4]),16);
            tracep->chgSData(oldp+5,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[5]),16);
            tracep->chgSData(oldp+6,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[6]),16);
            tracep->chgSData(oldp+7,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[7]),16);
            tracep->chgSData(oldp+8,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[8]),16);
            tracep->chgSData(oldp+9,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[9]),16);
            tracep->chgSData(oldp+10,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[10]),16);
            tracep->chgSData(oldp+11,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[11]),16);
            tracep->chgSData(oldp+12,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[12]),16);
            tracep->chgSData(oldp+13,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[13]),16);
            tracep->chgSData(oldp+14,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[14]),16);
            tracep->chgSData(oldp+15,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[15]),16);
            tracep->chgSData(oldp+16,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[16]),16);
            tracep->chgSData(oldp+17,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[17]),16);
            tracep->chgSData(oldp+18,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[18]),16);
            tracep->chgSData(oldp+19,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[19]),16);
            tracep->chgSData(oldp+20,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[20]),16);
            tracep->chgSData(oldp+21,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[21]),16);
            tracep->chgSData(oldp+22,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[22]),16);
            tracep->chgSData(oldp+23,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[23]),16);
            tracep->chgSData(oldp+24,(vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom[24]),16);
            tracep->chgSData(oldp+25,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[0]),16);
            tracep->chgSData(oldp+26,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[1]),16);
            tracep->chgSData(oldp+27,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[2]),16);
            tracep->chgSData(oldp+28,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[3]),16);
            tracep->chgSData(oldp+29,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[4]),16);
            tracep->chgSData(oldp+30,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[5]),16);
            tracep->chgSData(oldp+31,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[6]),16);
            tracep->chgSData(oldp+32,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[7]),16);
            tracep->chgSData(oldp+33,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[8]),16);
            tracep->chgSData(oldp+34,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[9]),16);
            tracep->chgSData(oldp+35,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[10]),16);
            tracep->chgSData(oldp+36,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[11]),16);
            tracep->chgSData(oldp+37,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[12]),16);
            tracep->chgSData(oldp+38,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[13]),16);
            tracep->chgSData(oldp+39,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[14]),16);
            tracep->chgSData(oldp+40,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[15]),16);
            tracep->chgSData(oldp+41,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[16]),16);
            tracep->chgSData(oldp+42,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[17]),16);
            tracep->chgSData(oldp+43,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[18]),16);
            tracep->chgSData(oldp+44,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[19]),16);
            tracep->chgSData(oldp+45,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[20]),16);
            tracep->chgSData(oldp+46,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[21]),16);
            tracep->chgSData(oldp+47,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[22]),16);
            tracep->chgSData(oldp+48,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[23]),16);
            tracep->chgSData(oldp+49,(vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom[24]),16);
            tracep->chgSData(oldp+50,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[0]),16);
            tracep->chgSData(oldp+51,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[1]),16);
            tracep->chgSData(oldp+52,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[2]),16);
            tracep->chgSData(oldp+53,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[3]),16);
            tracep->chgSData(oldp+54,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[4]),16);
            tracep->chgSData(oldp+55,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[5]),16);
            tracep->chgSData(oldp+56,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[6]),16);
            tracep->chgSData(oldp+57,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[7]),16);
            tracep->chgSData(oldp+58,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[8]),16);
            tracep->chgSData(oldp+59,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[9]),16);
            tracep->chgSData(oldp+60,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[10]),16);
            tracep->chgSData(oldp+61,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[11]),16);
            tracep->chgSData(oldp+62,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[12]),16);
            tracep->chgSData(oldp+63,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[13]),16);
            tracep->chgSData(oldp+64,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[14]),16);
            tracep->chgSData(oldp+65,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[15]),16);
            tracep->chgSData(oldp+66,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[16]),16);
            tracep->chgSData(oldp+67,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[17]),16);
            tracep->chgSData(oldp+68,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[18]),16);
            tracep->chgSData(oldp+69,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[19]),16);
            tracep->chgSData(oldp+70,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[20]),16);
            tracep->chgSData(oldp+71,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[21]),16);
            tracep->chgSData(oldp+72,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[22]),16);
            tracep->chgSData(oldp+73,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[23]),16);
            tracep->chgSData(oldp+74,(vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom[24]),16);
            tracep->chgSData(oldp+75,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[0]),16);
            tracep->chgSData(oldp+76,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[1]),16);
            tracep->chgSData(oldp+77,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[2]),16);
            tracep->chgSData(oldp+78,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[3]),16);
            tracep->chgSData(oldp+79,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[4]),16);
            tracep->chgSData(oldp+80,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[5]),16);
            tracep->chgSData(oldp+81,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[6]),16);
            tracep->chgSData(oldp+82,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[7]),16);
            tracep->chgSData(oldp+83,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[8]),16);
            tracep->chgSData(oldp+84,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[9]),16);
            tracep->chgSData(oldp+85,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[10]),16);
            tracep->chgSData(oldp+86,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[11]),16);
            tracep->chgSData(oldp+87,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[12]),16);
            tracep->chgSData(oldp+88,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[13]),16);
            tracep->chgSData(oldp+89,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[14]),16);
            tracep->chgSData(oldp+90,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[15]),16);
            tracep->chgSData(oldp+91,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[16]),16);
            tracep->chgSData(oldp+92,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[17]),16);
            tracep->chgSData(oldp+93,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[18]),16);
            tracep->chgSData(oldp+94,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[19]),16);
            tracep->chgSData(oldp+95,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[20]),16);
            tracep->chgSData(oldp+96,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[21]),16);
            tracep->chgSData(oldp+97,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[22]),16);
            tracep->chgSData(oldp+98,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[23]),16);
            tracep->chgSData(oldp+99,(vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom[24]),16);
            tracep->chgSData(oldp+100,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[0]),16);
            tracep->chgSData(oldp+101,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[1]),16);
            tracep->chgSData(oldp+102,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[2]),16);
            tracep->chgSData(oldp+103,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[3]),16);
            tracep->chgSData(oldp+104,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[4]),16);
            tracep->chgSData(oldp+105,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[5]),16);
            tracep->chgSData(oldp+106,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[6]),16);
            tracep->chgSData(oldp+107,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[7]),16);
            tracep->chgSData(oldp+108,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[8]),16);
            tracep->chgSData(oldp+109,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[9]),16);
            tracep->chgSData(oldp+110,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[10]),16);
            tracep->chgSData(oldp+111,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[11]),16);
            tracep->chgSData(oldp+112,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[12]),16);
            tracep->chgSData(oldp+113,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[13]),16);
            tracep->chgSData(oldp+114,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[14]),16);
            tracep->chgSData(oldp+115,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[15]),16);
            tracep->chgSData(oldp+116,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[16]),16);
            tracep->chgSData(oldp+117,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[17]),16);
            tracep->chgSData(oldp+118,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[18]),16);
            tracep->chgSData(oldp+119,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[19]),16);
            tracep->chgSData(oldp+120,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[20]),16);
            tracep->chgSData(oldp+121,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[21]),16);
            tracep->chgSData(oldp+122,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[22]),16);
            tracep->chgSData(oldp+123,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[23]),16);
            tracep->chgSData(oldp+124,(vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom[24]),16);
            tracep->chgSData(oldp+125,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[0]),16);
            tracep->chgSData(oldp+126,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[1]),16);
            tracep->chgSData(oldp+127,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[2]),16);
            tracep->chgSData(oldp+128,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[3]),16);
            tracep->chgSData(oldp+129,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[4]),16);
            tracep->chgSData(oldp+130,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[5]),16);
            tracep->chgSData(oldp+131,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[6]),16);
            tracep->chgSData(oldp+132,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[7]),16);
            tracep->chgSData(oldp+133,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[8]),16);
            tracep->chgSData(oldp+134,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[9]),16);
            tracep->chgSData(oldp+135,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[10]),16);
            tracep->chgSData(oldp+136,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[11]),16);
            tracep->chgSData(oldp+137,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[12]),16);
            tracep->chgSData(oldp+138,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[13]),16);
            tracep->chgSData(oldp+139,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[14]),16);
            tracep->chgSData(oldp+140,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[15]),16);
            tracep->chgSData(oldp+141,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[16]),16);
            tracep->chgSData(oldp+142,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[17]),16);
            tracep->chgSData(oldp+143,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[18]),16);
            tracep->chgSData(oldp+144,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[19]),16);
            tracep->chgSData(oldp+145,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[20]),16);
            tracep->chgSData(oldp+146,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[21]),16);
            tracep->chgSData(oldp+147,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[22]),16);
            tracep->chgSData(oldp+148,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[23]),16);
            tracep->chgSData(oldp+149,(vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom[24]),16);
        }
        if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[1U])) {
            tracep->chgCData(oldp+150,(vlSelf->conv1__DOT__window_out[0]),8);
            tracep->chgCData(oldp+151,(vlSelf->conv1__DOT__window_out[1]),8);
            tracep->chgCData(oldp+152,(vlSelf->conv1__DOT__window_out[2]),8);
            tracep->chgCData(oldp+153,(vlSelf->conv1__DOT__window_out[3]),8);
            tracep->chgCData(oldp+154,(vlSelf->conv1__DOT__window_out[4]),8);
            tracep->chgBit(oldp+155,(vlSelf->conv1__DOT__delay_data_out_valid_o));
            tracep->chgCData(oldp+156,(vlSelf->conv1__DOT____Vcellout__genblk2__BRA__0__KET____DOT__graylinebuffer_U__dout),8);
            tracep->chgCData(oldp+157,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[0]),8);
            tracep->chgCData(oldp+158,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[1]),8);
            tracep->chgCData(oldp+159,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[2]),8);
            tracep->chgCData(oldp+160,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[3]),8);
            tracep->chgCData(oldp+161,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[4]),8);
            tracep->chgCData(oldp+162,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[5]),8);
            tracep->chgCData(oldp+163,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[6]),8);
            tracep->chgCData(oldp+164,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[7]),8);
            tracep->chgCData(oldp+165,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[8]),8);
            tracep->chgCData(oldp+166,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[9]),8);
            tracep->chgCData(oldp+167,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[10]),8);
            tracep->chgCData(oldp+168,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[11]),8);
            tracep->chgCData(oldp+169,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[12]),8);
            tracep->chgCData(oldp+170,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[13]),8);
            tracep->chgCData(oldp+171,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[14]),8);
            tracep->chgCData(oldp+172,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[15]),8);
            tracep->chgCData(oldp+173,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[16]),8);
            tracep->chgCData(oldp+174,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[17]),8);
            tracep->chgCData(oldp+175,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[18]),8);
            tracep->chgCData(oldp+176,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[19]),8);
            tracep->chgCData(oldp+177,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[20]),8);
            tracep->chgCData(oldp+178,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[21]),8);
            tracep->chgCData(oldp+179,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[22]),8);
            tracep->chgCData(oldp+180,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[23]),8);
            tracep->chgCData(oldp+181,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[24]),8);
            tracep->chgCData(oldp+182,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[25]),8);
            tracep->chgCData(oldp+183,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[26]),8);
            tracep->chgCData(oldp+184,(vlSelf->conv1__DOT__genblk2__BRA__0__KET____DOT__graylinebuffer_U__DOT__buffer[27]),8);
            tracep->chgCData(oldp+185,(vlSelf->conv1__DOT____Vcellout__genblk2__BRA__1__KET____DOT__graylinebuffer_U__dout),8);
            tracep->chgCData(oldp+186,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[0]),8);
            tracep->chgCData(oldp+187,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[1]),8);
            tracep->chgCData(oldp+188,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[2]),8);
            tracep->chgCData(oldp+189,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[3]),8);
            tracep->chgCData(oldp+190,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[4]),8);
            tracep->chgCData(oldp+191,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[5]),8);
            tracep->chgCData(oldp+192,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[6]),8);
            tracep->chgCData(oldp+193,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[7]),8);
            tracep->chgCData(oldp+194,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[8]),8);
            tracep->chgCData(oldp+195,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[9]),8);
            tracep->chgCData(oldp+196,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[10]),8);
            tracep->chgCData(oldp+197,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[11]),8);
            tracep->chgCData(oldp+198,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[12]),8);
            tracep->chgCData(oldp+199,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[13]),8);
            tracep->chgCData(oldp+200,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[14]),8);
            tracep->chgCData(oldp+201,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[15]),8);
            tracep->chgCData(oldp+202,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[16]),8);
            tracep->chgCData(oldp+203,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[17]),8);
            tracep->chgCData(oldp+204,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[18]),8);
            tracep->chgCData(oldp+205,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[19]),8);
            tracep->chgCData(oldp+206,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[20]),8);
            tracep->chgCData(oldp+207,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[21]),8);
            tracep->chgCData(oldp+208,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[22]),8);
            tracep->chgCData(oldp+209,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[23]),8);
            tracep->chgCData(oldp+210,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[24]),8);
            tracep->chgCData(oldp+211,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[25]),8);
            tracep->chgCData(oldp+212,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[26]),8);
            tracep->chgCData(oldp+213,(vlSelf->conv1__DOT__genblk2__BRA__1__KET____DOT__graylinebuffer_U__DOT__buffer[27]),8);
            tracep->chgCData(oldp+214,(vlSelf->conv1__DOT____Vcellout__genblk2__BRA__2__KET____DOT__graylinebuffer_U__dout),8);
            tracep->chgCData(oldp+215,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[0]),8);
            tracep->chgCData(oldp+216,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[1]),8);
            tracep->chgCData(oldp+217,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[2]),8);
            tracep->chgCData(oldp+218,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[3]),8);
            tracep->chgCData(oldp+219,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[4]),8);
            tracep->chgCData(oldp+220,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[5]),8);
            tracep->chgCData(oldp+221,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[6]),8);
            tracep->chgCData(oldp+222,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[7]),8);
            tracep->chgCData(oldp+223,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[8]),8);
            tracep->chgCData(oldp+224,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[9]),8);
            tracep->chgCData(oldp+225,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[10]),8);
            tracep->chgCData(oldp+226,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[11]),8);
            tracep->chgCData(oldp+227,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[12]),8);
            tracep->chgCData(oldp+228,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[13]),8);
            tracep->chgCData(oldp+229,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[14]),8);
            tracep->chgCData(oldp+230,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[15]),8);
            tracep->chgCData(oldp+231,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[16]),8);
            tracep->chgCData(oldp+232,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[17]),8);
            tracep->chgCData(oldp+233,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[18]),8);
            tracep->chgCData(oldp+234,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[19]),8);
            tracep->chgCData(oldp+235,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[20]),8);
            tracep->chgCData(oldp+236,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[21]),8);
            tracep->chgCData(oldp+237,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[22]),8);
            tracep->chgCData(oldp+238,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[23]),8);
            tracep->chgCData(oldp+239,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[24]),8);
            tracep->chgCData(oldp+240,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[25]),8);
            tracep->chgCData(oldp+241,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[26]),8);
            tracep->chgCData(oldp+242,(vlSelf->conv1__DOT__genblk2__BRA__2__KET____DOT__graylinebuffer_U__DOT__buffer[27]),8);
            tracep->chgCData(oldp+243,(vlSelf->conv1__DOT____Vcellout__genblk2__BRA__3__KET____DOT__graylinebuffer_U__dout),8);
            tracep->chgCData(oldp+244,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[0]),8);
            tracep->chgCData(oldp+245,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[1]),8);
            tracep->chgCData(oldp+246,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[2]),8);
            tracep->chgCData(oldp+247,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[3]),8);
            tracep->chgCData(oldp+248,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[4]),8);
            tracep->chgCData(oldp+249,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[5]),8);
            tracep->chgCData(oldp+250,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[6]),8);
            tracep->chgCData(oldp+251,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[7]),8);
            tracep->chgCData(oldp+252,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[8]),8);
            tracep->chgCData(oldp+253,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[9]),8);
            tracep->chgCData(oldp+254,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[10]),8);
            tracep->chgCData(oldp+255,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[11]),8);
            tracep->chgCData(oldp+256,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[12]),8);
            tracep->chgCData(oldp+257,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[13]),8);
            tracep->chgCData(oldp+258,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[14]),8);
            tracep->chgCData(oldp+259,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[15]),8);
            tracep->chgCData(oldp+260,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[16]),8);
            tracep->chgCData(oldp+261,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[17]),8);
            tracep->chgCData(oldp+262,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[18]),8);
            tracep->chgCData(oldp+263,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[19]),8);
            tracep->chgCData(oldp+264,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[20]),8);
            tracep->chgCData(oldp+265,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[21]),8);
            tracep->chgCData(oldp+266,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[22]),8);
            tracep->chgCData(oldp+267,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[23]),8);
            tracep->chgCData(oldp+268,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[24]),8);
            tracep->chgCData(oldp+269,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[25]),8);
            tracep->chgCData(oldp+270,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[26]),8);
            tracep->chgCData(oldp+271,(vlSelf->conv1__DOT__genblk2__BRA__3__KET____DOT__graylinebuffer_U__DOT__buffer[27]),8);
            tracep->chgCData(oldp+272,(vlSelf->conv1__DOT____Vcellout__genblk2__BRA__4__KET____DOT__graylinebuffer_U__dout),8);
            tracep->chgCData(oldp+273,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[0]),8);
            tracep->chgCData(oldp+274,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[1]),8);
            tracep->chgCData(oldp+275,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[2]),8);
            tracep->chgCData(oldp+276,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[3]),8);
            tracep->chgCData(oldp+277,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[4]),8);
            tracep->chgCData(oldp+278,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[5]),8);
            tracep->chgCData(oldp+279,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[6]),8);
            tracep->chgCData(oldp+280,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[7]),8);
            tracep->chgCData(oldp+281,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[8]),8);
            tracep->chgCData(oldp+282,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[9]),8);
            tracep->chgCData(oldp+283,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[10]),8);
            tracep->chgCData(oldp+284,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[11]),8);
            tracep->chgCData(oldp+285,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[12]),8);
            tracep->chgCData(oldp+286,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[13]),8);
            tracep->chgCData(oldp+287,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[14]),8);
            tracep->chgCData(oldp+288,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[15]),8);
            tracep->chgCData(oldp+289,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[16]),8);
            tracep->chgCData(oldp+290,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[17]),8);
            tracep->chgCData(oldp+291,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[18]),8);
            tracep->chgCData(oldp+292,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[19]),8);
            tracep->chgCData(oldp+293,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[20]),8);
            tracep->chgCData(oldp+294,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[21]),8);
            tracep->chgCData(oldp+295,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[22]),8);
            tracep->chgCData(oldp+296,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[23]),8);
            tracep->chgCData(oldp+297,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[24]),8);
            tracep->chgCData(oldp+298,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[25]),8);
            tracep->chgCData(oldp+299,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[26]),8);
            tracep->chgCData(oldp+300,(vlSelf->conv1__DOT__genblk2__BRA__4__KET____DOT__graylinebuffer_U__DOT__buffer[27]),8);
        }
        if (VL_UNLIKELY(vlSelf->__Vm_traceActivity[2U])) {
            tracep->chgCData(oldp+301,(vlSelf->conv1__DOT__wr_addr),5);
            tracep->chgCData(oldp+302,(vlSelf->conv1__DOT__rd_addr),5);
            tracep->chgCData(oldp+303,((0x1fU & ((IData)(2U) 
                                                 + (IData)(vlSelf->conv1__DOT__wr_addr)))),5);
            tracep->chgCData(oldp+304,(vlSelf->conv1__DOT__window
                                       [0U][0U]),8);
            tracep->chgCData(oldp+305,(vlSelf->conv1__DOT__window
                                       [0U][1U]),8);
            tracep->chgCData(oldp+306,(vlSelf->conv1__DOT__window
                                       [0U][2U]),8);
            tracep->chgCData(oldp+307,(vlSelf->conv1__DOT__window
                                       [0U][3U]),8);
            tracep->chgCData(oldp+308,(vlSelf->conv1__DOT__window
                                       [0U][4U]),8);
            tracep->chgCData(oldp+309,(vlSelf->conv1__DOT__window
                                       [1U][0U]),8);
            tracep->chgCData(oldp+310,(vlSelf->conv1__DOT__window
                                       [1U][1U]),8);
            tracep->chgCData(oldp+311,(vlSelf->conv1__DOT__window
                                       [1U][2U]),8);
            tracep->chgCData(oldp+312,(vlSelf->conv1__DOT__window
                                       [1U][3U]),8);
            tracep->chgCData(oldp+313,(vlSelf->conv1__DOT__window
                                       [1U][4U]),8);
            tracep->chgCData(oldp+314,(vlSelf->conv1__DOT__window
                                       [2U][0U]),8);
            tracep->chgCData(oldp+315,(vlSelf->conv1__DOT__window
                                       [2U][1U]),8);
            tracep->chgCData(oldp+316,(vlSelf->conv1__DOT__window
                                       [2U][2U]),8);
            tracep->chgCData(oldp+317,(vlSelf->conv1__DOT__window
                                       [2U][3U]),8);
            tracep->chgCData(oldp+318,(vlSelf->conv1__DOT__window
                                       [2U][4U]),8);
            tracep->chgCData(oldp+319,(vlSelf->conv1__DOT__window
                                       [3U][0U]),8);
            tracep->chgCData(oldp+320,(vlSelf->conv1__DOT__window
                                       [3U][1U]),8);
            tracep->chgCData(oldp+321,(vlSelf->conv1__DOT__window
                                       [3U][2U]),8);
            tracep->chgCData(oldp+322,(vlSelf->conv1__DOT__window
                                       [3U][3U]),8);
            tracep->chgCData(oldp+323,(vlSelf->conv1__DOT__window
                                       [3U][4U]),8);
            tracep->chgCData(oldp+324,(vlSelf->conv1__DOT__window
                                       [4U][0U]),8);
            tracep->chgCData(oldp+325,(vlSelf->conv1__DOT__window
                                       [4U][1U]),8);
            tracep->chgCData(oldp+326,(vlSelf->conv1__DOT__window
                                       [4U][2U]),8);
            tracep->chgCData(oldp+327,(vlSelf->conv1__DOT__window
                                       [4U][3U]),8);
            tracep->chgCData(oldp+328,(vlSelf->conv1__DOT__window
                                       [4U][4U]),8);
            tracep->chgIData(oldp+329,(vlSelf->conv1__DOT__i),32);
            tracep->chgIData(oldp+330,(vlSelf->conv1__DOT__j),32);
            tracep->chgCData(oldp+331,(vlSelf->conv1__DOT__x_cnt),5);
            tracep->chgCData(oldp+332,(vlSelf->conv1__DOT__y_cnt),5);
            tracep->chgSData(oldp+333,(((0x18U >= (IData)(vlSelf->conv1__DOT__rom_cnt))
                                         ? vlSelf->conv1__DOT__weights_rom_u1__DOT__para_rom
                                        [vlSelf->conv1__DOT__rom_cnt]
                                         : 0U)),16);
            tracep->chgSData(oldp+334,(((0x18U >= (IData)(vlSelf->conv1__DOT__rom_cnt))
                                         ? vlSelf->conv1__DOT__weights_rom_u2__DOT__para_rom
                                        [vlSelf->conv1__DOT__rom_cnt]
                                         : 0U)),16);
            tracep->chgSData(oldp+335,(((0x18U >= (IData)(vlSelf->conv1__DOT__rom_cnt))
                                         ? vlSelf->conv1__DOT__weights_rom_u3__DOT__para_rom
                                        [vlSelf->conv1__DOT__rom_cnt]
                                         : 0U)),16);
            tracep->chgSData(oldp+336,(((0x18U >= (IData)(vlSelf->conv1__DOT__rom_cnt))
                                         ? vlSelf->conv1__DOT__weights_rom_u4__DOT__para_rom
                                        [vlSelf->conv1__DOT__rom_cnt]
                                         : 0U)),16);
            tracep->chgSData(oldp+337,(((0x18U >= (IData)(vlSelf->conv1__DOT__rom_cnt))
                                         ? vlSelf->conv1__DOT__weights_rom_u5__DOT__para_rom
                                        [vlSelf->conv1__DOT__rom_cnt]
                                         : 0U)),16);
            tracep->chgSData(oldp+338,(((0x18U >= (IData)(vlSelf->conv1__DOT__rom_cnt))
                                         ? vlSelf->conv1__DOT__weights_rom_u6__DOT__para_rom
                                        [vlSelf->conv1__DOT__rom_cnt]
                                         : 0U)),16);
            tracep->chgSData(oldp+339,(vlSelf->conv1__DOT__c1_w_1
                                       [0U][0U]),16);
            tracep->chgSData(oldp+340,(vlSelf->conv1__DOT__c1_w_1
                                       [0U][1U]),16);
            tracep->chgSData(oldp+341,(vlSelf->conv1__DOT__c1_w_1
                                       [0U][2U]),16);
            tracep->chgSData(oldp+342,(vlSelf->conv1__DOT__c1_w_1
                                       [0U][3U]),16);
            tracep->chgSData(oldp+343,(vlSelf->conv1__DOT__c1_w_1
                                       [0U][4U]),16);
            tracep->chgSData(oldp+344,(vlSelf->conv1__DOT__c1_w_1
                                       [1U][0U]),16);
            tracep->chgSData(oldp+345,(vlSelf->conv1__DOT__c1_w_1
                                       [1U][1U]),16);
            tracep->chgSData(oldp+346,(vlSelf->conv1__DOT__c1_w_1
                                       [1U][2U]),16);
            tracep->chgSData(oldp+347,(vlSelf->conv1__DOT__c1_w_1
                                       [1U][3U]),16);
            tracep->chgSData(oldp+348,(vlSelf->conv1__DOT__c1_w_1
                                       [1U][4U]),16);
            tracep->chgSData(oldp+349,(vlSelf->conv1__DOT__c1_w_1
                                       [2U][0U]),16);
            tracep->chgSData(oldp+350,(vlSelf->conv1__DOT__c1_w_1
                                       [2U][1U]),16);
            tracep->chgSData(oldp+351,(vlSelf->conv1__DOT__c1_w_1
                                       [2U][2U]),16);
            tracep->chgSData(oldp+352,(vlSelf->conv1__DOT__c1_w_1
                                       [2U][3U]),16);
            tracep->chgSData(oldp+353,(vlSelf->conv1__DOT__c1_w_1
                                       [2U][4U]),16);
            tracep->chgSData(oldp+354,(vlSelf->conv1__DOT__c1_w_1
                                       [3U][0U]),16);
            tracep->chgSData(oldp+355,(vlSelf->conv1__DOT__c1_w_1
                                       [3U][1U]),16);
            tracep->chgSData(oldp+356,(vlSelf->conv1__DOT__c1_w_1
                                       [3U][2U]),16);
            tracep->chgSData(oldp+357,(vlSelf->conv1__DOT__c1_w_1
                                       [3U][3U]),16);
            tracep->chgSData(oldp+358,(vlSelf->conv1__DOT__c1_w_1
                                       [3U][4U]),16);
            tracep->chgSData(oldp+359,(vlSelf->conv1__DOT__c1_w_1
                                       [4U][0U]),16);
            tracep->chgSData(oldp+360,(vlSelf->conv1__DOT__c1_w_1
                                       [4U][1U]),16);
            tracep->chgSData(oldp+361,(vlSelf->conv1__DOT__c1_w_1
                                       [4U][2U]),16);
            tracep->chgSData(oldp+362,(vlSelf->conv1__DOT__c1_w_1
                                       [4U][3U]),16);
            tracep->chgSData(oldp+363,(vlSelf->conv1__DOT__c1_w_1
                                       [4U][4U]),16);
            tracep->chgSData(oldp+364,(vlSelf->conv1__DOT__c1_w_2
                                       [0U][0U]),16);
            tracep->chgSData(oldp+365,(vlSelf->conv1__DOT__c1_w_2
                                       [0U][1U]),16);
            tracep->chgSData(oldp+366,(vlSelf->conv1__DOT__c1_w_2
                                       [0U][2U]),16);
            tracep->chgSData(oldp+367,(vlSelf->conv1__DOT__c1_w_2
                                       [0U][3U]),16);
            tracep->chgSData(oldp+368,(vlSelf->conv1__DOT__c1_w_2
                                       [0U][4U]),16);
            tracep->chgSData(oldp+369,(vlSelf->conv1__DOT__c1_w_2
                                       [1U][0U]),16);
            tracep->chgSData(oldp+370,(vlSelf->conv1__DOT__c1_w_2
                                       [1U][1U]),16);
            tracep->chgSData(oldp+371,(vlSelf->conv1__DOT__c1_w_2
                                       [1U][2U]),16);
            tracep->chgSData(oldp+372,(vlSelf->conv1__DOT__c1_w_2
                                       [1U][3U]),16);
            tracep->chgSData(oldp+373,(vlSelf->conv1__DOT__c1_w_2
                                       [1U][4U]),16);
            tracep->chgSData(oldp+374,(vlSelf->conv1__DOT__c1_w_2
                                       [2U][0U]),16);
            tracep->chgSData(oldp+375,(vlSelf->conv1__DOT__c1_w_2
                                       [2U][1U]),16);
            tracep->chgSData(oldp+376,(vlSelf->conv1__DOT__c1_w_2
                                       [2U][2U]),16);
            tracep->chgSData(oldp+377,(vlSelf->conv1__DOT__c1_w_2
                                       [2U][3U]),16);
            tracep->chgSData(oldp+378,(vlSelf->conv1__DOT__c1_w_2
                                       [2U][4U]),16);
            tracep->chgSData(oldp+379,(vlSelf->conv1__DOT__c1_w_2
                                       [3U][0U]),16);
            tracep->chgSData(oldp+380,(vlSelf->conv1__DOT__c1_w_2
                                       [3U][1U]),16);
            tracep->chgSData(oldp+381,(vlSelf->conv1__DOT__c1_w_2
                                       [3U][2U]),16);
            tracep->chgSData(oldp+382,(vlSelf->conv1__DOT__c1_w_2
                                       [3U][3U]),16);
            tracep->chgSData(oldp+383,(vlSelf->conv1__DOT__c1_w_2
                                       [3U][4U]),16);
            tracep->chgSData(oldp+384,(vlSelf->conv1__DOT__c1_w_2
                                       [4U][0U]),16);
            tracep->chgSData(oldp+385,(vlSelf->conv1__DOT__c1_w_2
                                       [4U][1U]),16);
            tracep->chgSData(oldp+386,(vlSelf->conv1__DOT__c1_w_2
                                       [4U][2U]),16);
            tracep->chgSData(oldp+387,(vlSelf->conv1__DOT__c1_w_2
                                       [4U][3U]),16);
            tracep->chgSData(oldp+388,(vlSelf->conv1__DOT__c1_w_2
                                       [4U][4U]),16);
            tracep->chgSData(oldp+389,(vlSelf->conv1__DOT__c1_w_3
                                       [0U][0U]),16);
            tracep->chgSData(oldp+390,(vlSelf->conv1__DOT__c1_w_3
                                       [0U][1U]),16);
            tracep->chgSData(oldp+391,(vlSelf->conv1__DOT__c1_w_3
                                       [0U][2U]),16);
            tracep->chgSData(oldp+392,(vlSelf->conv1__DOT__c1_w_3
                                       [0U][3U]),16);
            tracep->chgSData(oldp+393,(vlSelf->conv1__DOT__c1_w_3
                                       [0U][4U]),16);
            tracep->chgSData(oldp+394,(vlSelf->conv1__DOT__c1_w_3
                                       [1U][0U]),16);
            tracep->chgSData(oldp+395,(vlSelf->conv1__DOT__c1_w_3
                                       [1U][1U]),16);
            tracep->chgSData(oldp+396,(vlSelf->conv1__DOT__c1_w_3
                                       [1U][2U]),16);
            tracep->chgSData(oldp+397,(vlSelf->conv1__DOT__c1_w_3
                                       [1U][3U]),16);
            tracep->chgSData(oldp+398,(vlSelf->conv1__DOT__c1_w_3
                                       [1U][4U]),16);
            tracep->chgSData(oldp+399,(vlSelf->conv1__DOT__c1_w_3
                                       [2U][0U]),16);
            tracep->chgSData(oldp+400,(vlSelf->conv1__DOT__c1_w_3
                                       [2U][1U]),16);
            tracep->chgSData(oldp+401,(vlSelf->conv1__DOT__c1_w_3
                                       [2U][2U]),16);
            tracep->chgSData(oldp+402,(vlSelf->conv1__DOT__c1_w_3
                                       [2U][3U]),16);
            tracep->chgSData(oldp+403,(vlSelf->conv1__DOT__c1_w_3
                                       [2U][4U]),16);
            tracep->chgSData(oldp+404,(vlSelf->conv1__DOT__c1_w_3
                                       [3U][0U]),16);
            tracep->chgSData(oldp+405,(vlSelf->conv1__DOT__c1_w_3
                                       [3U][1U]),16);
            tracep->chgSData(oldp+406,(vlSelf->conv1__DOT__c1_w_3
                                       [3U][2U]),16);
            tracep->chgSData(oldp+407,(vlSelf->conv1__DOT__c1_w_3
                                       [3U][3U]),16);
            tracep->chgSData(oldp+408,(vlSelf->conv1__DOT__c1_w_3
                                       [3U][4U]),16);
            tracep->chgSData(oldp+409,(vlSelf->conv1__DOT__c1_w_3
                                       [4U][0U]),16);
            tracep->chgSData(oldp+410,(vlSelf->conv1__DOT__c1_w_3
                                       [4U][1U]),16);
            tracep->chgSData(oldp+411,(vlSelf->conv1__DOT__c1_w_3
                                       [4U][2U]),16);
            tracep->chgSData(oldp+412,(vlSelf->conv1__DOT__c1_w_3
                                       [4U][3U]),16);
            tracep->chgSData(oldp+413,(vlSelf->conv1__DOT__c1_w_3
                                       [4U][4U]),16);
            tracep->chgSData(oldp+414,(vlSelf->conv1__DOT__c1_w_4
                                       [0U][0U]),16);
            tracep->chgSData(oldp+415,(vlSelf->conv1__DOT__c1_w_4
                                       [0U][1U]),16);
            tracep->chgSData(oldp+416,(vlSelf->conv1__DOT__c1_w_4
                                       [0U][2U]),16);
            tracep->chgSData(oldp+417,(vlSelf->conv1__DOT__c1_w_4
                                       [0U][3U]),16);
            tracep->chgSData(oldp+418,(vlSelf->conv1__DOT__c1_w_4
                                       [0U][4U]),16);
            tracep->chgSData(oldp+419,(vlSelf->conv1__DOT__c1_w_4
                                       [1U][0U]),16);
            tracep->chgSData(oldp+420,(vlSelf->conv1__DOT__c1_w_4
                                       [1U][1U]),16);
            tracep->chgSData(oldp+421,(vlSelf->conv1__DOT__c1_w_4
                                       [1U][2U]),16);
            tracep->chgSData(oldp+422,(vlSelf->conv1__DOT__c1_w_4
                                       [1U][3U]),16);
            tracep->chgSData(oldp+423,(vlSelf->conv1__DOT__c1_w_4
                                       [1U][4U]),16);
            tracep->chgSData(oldp+424,(vlSelf->conv1__DOT__c1_w_4
                                       [2U][0U]),16);
            tracep->chgSData(oldp+425,(vlSelf->conv1__DOT__c1_w_4
                                       [2U][1U]),16);
            tracep->chgSData(oldp+426,(vlSelf->conv1__DOT__c1_w_4
                                       [2U][2U]),16);
            tracep->chgSData(oldp+427,(vlSelf->conv1__DOT__c1_w_4
                                       [2U][3U]),16);
            tracep->chgSData(oldp+428,(vlSelf->conv1__DOT__c1_w_4
                                       [2U][4U]),16);
            tracep->chgSData(oldp+429,(vlSelf->conv1__DOT__c1_w_4
                                       [3U][0U]),16);
            tracep->chgSData(oldp+430,(vlSelf->conv1__DOT__c1_w_4
                                       [3U][1U]),16);
            tracep->chgSData(oldp+431,(vlSelf->conv1__DOT__c1_w_4
                                       [3U][2U]),16);
            tracep->chgSData(oldp+432,(vlSelf->conv1__DOT__c1_w_4
                                       [3U][3U]),16);
            tracep->chgSData(oldp+433,(vlSelf->conv1__DOT__c1_w_4
                                       [3U][4U]),16);
            tracep->chgSData(oldp+434,(vlSelf->conv1__DOT__c1_w_4
                                       [4U][0U]),16);
            tracep->chgSData(oldp+435,(vlSelf->conv1__DOT__c1_w_4
                                       [4U][1U]),16);
            tracep->chgSData(oldp+436,(vlSelf->conv1__DOT__c1_w_4
                                       [4U][2U]),16);
            tracep->chgSData(oldp+437,(vlSelf->conv1__DOT__c1_w_4
                                       [4U][3U]),16);
            tracep->chgSData(oldp+438,(vlSelf->conv1__DOT__c1_w_4
                                       [4U][4U]),16);
            tracep->chgSData(oldp+439,(vlSelf->conv1__DOT__c1_w_5
                                       [0U][0U]),16);
            tracep->chgSData(oldp+440,(vlSelf->conv1__DOT__c1_w_5
                                       [0U][1U]),16);
            tracep->chgSData(oldp+441,(vlSelf->conv1__DOT__c1_w_5
                                       [0U][2U]),16);
            tracep->chgSData(oldp+442,(vlSelf->conv1__DOT__c1_w_5
                                       [0U][3U]),16);
            tracep->chgSData(oldp+443,(vlSelf->conv1__DOT__c1_w_5
                                       [0U][4U]),16);
            tracep->chgSData(oldp+444,(vlSelf->conv1__DOT__c1_w_5
                                       [1U][0U]),16);
            tracep->chgSData(oldp+445,(vlSelf->conv1__DOT__c1_w_5
                                       [1U][1U]),16);
            tracep->chgSData(oldp+446,(vlSelf->conv1__DOT__c1_w_5
                                       [1U][2U]),16);
            tracep->chgSData(oldp+447,(vlSelf->conv1__DOT__c1_w_5
                                       [1U][3U]),16);
            tracep->chgSData(oldp+448,(vlSelf->conv1__DOT__c1_w_5
                                       [1U][4U]),16);
            tracep->chgSData(oldp+449,(vlSelf->conv1__DOT__c1_w_5
                                       [2U][0U]),16);
            tracep->chgSData(oldp+450,(vlSelf->conv1__DOT__c1_w_5
                                       [2U][1U]),16);
            tracep->chgSData(oldp+451,(vlSelf->conv1__DOT__c1_w_5
                                       [2U][2U]),16);
            tracep->chgSData(oldp+452,(vlSelf->conv1__DOT__c1_w_5
                                       [2U][3U]),16);
            tracep->chgSData(oldp+453,(vlSelf->conv1__DOT__c1_w_5
                                       [2U][4U]),16);
            tracep->chgSData(oldp+454,(vlSelf->conv1__DOT__c1_w_5
                                       [3U][0U]),16);
            tracep->chgSData(oldp+455,(vlSelf->conv1__DOT__c1_w_5
                                       [3U][1U]),16);
            tracep->chgSData(oldp+456,(vlSelf->conv1__DOT__c1_w_5
                                       [3U][2U]),16);
            tracep->chgSData(oldp+457,(vlSelf->conv1__DOT__c1_w_5
                                       [3U][3U]),16);
            tracep->chgSData(oldp+458,(vlSelf->conv1__DOT__c1_w_5
                                       [3U][4U]),16);
            tracep->chgSData(oldp+459,(vlSelf->conv1__DOT__c1_w_5
                                       [4U][0U]),16);
            tracep->chgSData(oldp+460,(vlSelf->conv1__DOT__c1_w_5
                                       [4U][1U]),16);
            tracep->chgSData(oldp+461,(vlSelf->conv1__DOT__c1_w_5
                                       [4U][2U]),16);
            tracep->chgSData(oldp+462,(vlSelf->conv1__DOT__c1_w_5
                                       [4U][3U]),16);
            tracep->chgSData(oldp+463,(vlSelf->conv1__DOT__c1_w_5
                                       [4U][4U]),16);
            tracep->chgSData(oldp+464,(vlSelf->conv1__DOT__c1_w_6
                                       [0U][0U]),16);
            tracep->chgSData(oldp+465,(vlSelf->conv1__DOT__c1_w_6
                                       [0U][1U]),16);
            tracep->chgSData(oldp+466,(vlSelf->conv1__DOT__c1_w_6
                                       [0U][2U]),16);
            tracep->chgSData(oldp+467,(vlSelf->conv1__DOT__c1_w_6
                                       [0U][3U]),16);
            tracep->chgSData(oldp+468,(vlSelf->conv1__DOT__c1_w_6
                                       [0U][4U]),16);
            tracep->chgSData(oldp+469,(vlSelf->conv1__DOT__c1_w_6
                                       [1U][0U]),16);
            tracep->chgSData(oldp+470,(vlSelf->conv1__DOT__c1_w_6
                                       [1U][1U]),16);
            tracep->chgSData(oldp+471,(vlSelf->conv1__DOT__c1_w_6
                                       [1U][2U]),16);
            tracep->chgSData(oldp+472,(vlSelf->conv1__DOT__c1_w_6
                                       [1U][3U]),16);
            tracep->chgSData(oldp+473,(vlSelf->conv1__DOT__c1_w_6
                                       [1U][4U]),16);
            tracep->chgSData(oldp+474,(vlSelf->conv1__DOT__c1_w_6
                                       [2U][0U]),16);
            tracep->chgSData(oldp+475,(vlSelf->conv1__DOT__c1_w_6
                                       [2U][1U]),16);
            tracep->chgSData(oldp+476,(vlSelf->conv1__DOT__c1_w_6
                                       [2U][2U]),16);
            tracep->chgSData(oldp+477,(vlSelf->conv1__DOT__c1_w_6
                                       [2U][3U]),16);
            tracep->chgSData(oldp+478,(vlSelf->conv1__DOT__c1_w_6
                                       [2U][4U]),16);
            tracep->chgSData(oldp+479,(vlSelf->conv1__DOT__c1_w_6
                                       [3U][0U]),16);
            tracep->chgSData(oldp+480,(vlSelf->conv1__DOT__c1_w_6
                                       [3U][1U]),16);
            tracep->chgSData(oldp+481,(vlSelf->conv1__DOT__c1_w_6
                                       [3U][2U]),16);
            tracep->chgSData(oldp+482,(vlSelf->conv1__DOT__c1_w_6
                                       [3U][3U]),16);
            tracep->chgSData(oldp+483,(vlSelf->conv1__DOT__c1_w_6
                                       [3U][4U]),16);
            tracep->chgSData(oldp+484,(vlSelf->conv1__DOT__c1_w_6
                                       [4U][0U]),16);
            tracep->chgSData(oldp+485,(vlSelf->conv1__DOT__c1_w_6
                                       [4U][1U]),16);
            tracep->chgSData(oldp+486,(vlSelf->conv1__DOT__c1_w_6
                                       [4U][2U]),16);
            tracep->chgSData(oldp+487,(vlSelf->conv1__DOT__c1_w_6
                                       [4U][3U]),16);
            tracep->chgSData(oldp+488,(vlSelf->conv1__DOT__c1_w_6
                                       [4U][4U]),16);
            tracep->chgCData(oldp+489,(vlSelf->conv1__DOT__rom_cnt),5);
            tracep->chgIData(oldp+490,(vlSelf->conv1__DOT__window_mul_result_1
                                       [0U][0U]),32);
            tracep->chgIData(oldp+491,(vlSelf->conv1__DOT__window_mul_result_1
                                       [0U][1U]),32);
            tracep->chgIData(oldp+492,(vlSelf->conv1__DOT__window_mul_result_1
                                       [0U][2U]),32);
            tracep->chgIData(oldp+493,(vlSelf->conv1__DOT__window_mul_result_1
                                       [0U][3U]),32);
            tracep->chgIData(oldp+494,(vlSelf->conv1__DOT__window_mul_result_1
                                       [0U][4U]),32);
            tracep->chgIData(oldp+495,(vlSelf->conv1__DOT__window_mul_result_1
                                       [1U][0U]),32);
            tracep->chgIData(oldp+496,(vlSelf->conv1__DOT__window_mul_result_1
                                       [1U][1U]),32);
            tracep->chgIData(oldp+497,(vlSelf->conv1__DOT__window_mul_result_1
                                       [1U][2U]),32);
            tracep->chgIData(oldp+498,(vlSelf->conv1__DOT__window_mul_result_1
                                       [1U][3U]),32);
            tracep->chgIData(oldp+499,(vlSelf->conv1__DOT__window_mul_result_1
                                       [1U][4U]),32);
            tracep->chgIData(oldp+500,(vlSelf->conv1__DOT__window_mul_result_1
                                       [2U][0U]),32);
            tracep->chgIData(oldp+501,(vlSelf->conv1__DOT__window_mul_result_1
                                       [2U][1U]),32);
            tracep->chgIData(oldp+502,(vlSelf->conv1__DOT__window_mul_result_1
                                       [2U][2U]),32);
            tracep->chgIData(oldp+503,(vlSelf->conv1__DOT__window_mul_result_1
                                       [2U][3U]),32);
            tracep->chgIData(oldp+504,(vlSelf->conv1__DOT__window_mul_result_1
                                       [2U][4U]),32);
            tracep->chgIData(oldp+505,(vlSelf->conv1__DOT__window_mul_result_1
                                       [3U][0U]),32);
            tracep->chgIData(oldp+506,(vlSelf->conv1__DOT__window_mul_result_1
                                       [3U][1U]),32);
            tracep->chgIData(oldp+507,(vlSelf->conv1__DOT__window_mul_result_1
                                       [3U][2U]),32);
            tracep->chgIData(oldp+508,(vlSelf->conv1__DOT__window_mul_result_1
                                       [3U][3U]),32);
            tracep->chgIData(oldp+509,(vlSelf->conv1__DOT__window_mul_result_1
                                       [3U][4U]),32);
            tracep->chgIData(oldp+510,(vlSelf->conv1__DOT__window_mul_result_1
                                       [4U][0U]),32);
            tracep->chgIData(oldp+511,(vlSelf->conv1__DOT__window_mul_result_1
                                       [4U][1U]),32);
            tracep->chgIData(oldp+512,(vlSelf->conv1__DOT__window_mul_result_1
                                       [4U][2U]),32);
            tracep->chgIData(oldp+513,(vlSelf->conv1__DOT__window_mul_result_1
                                       [4U][3U]),32);
            tracep->chgIData(oldp+514,(vlSelf->conv1__DOT__window_mul_result_1
                                       [4U][4U]),32);
            tracep->chgIData(oldp+515,(vlSelf->conv1__DOT__window_mul_result_2
                                       [0U][0U]),32);
            tracep->chgIData(oldp+516,(vlSelf->conv1__DOT__window_mul_result_2
                                       [0U][1U]),32);
            tracep->chgIData(oldp+517,(vlSelf->conv1__DOT__window_mul_result_2
                                       [0U][2U]),32);
            tracep->chgIData(oldp+518,(vlSelf->conv1__DOT__window_mul_result_2
                                       [0U][3U]),32);
            tracep->chgIData(oldp+519,(vlSelf->conv1__DOT__window_mul_result_2
                                       [0U][4U]),32);
            tracep->chgIData(oldp+520,(vlSelf->conv1__DOT__window_mul_result_2
                                       [1U][0U]),32);
            tracep->chgIData(oldp+521,(vlSelf->conv1__DOT__window_mul_result_2
                                       [1U][1U]),32);
            tracep->chgIData(oldp+522,(vlSelf->conv1__DOT__window_mul_result_2
                                       [1U][2U]),32);
            tracep->chgIData(oldp+523,(vlSelf->conv1__DOT__window_mul_result_2
                                       [1U][3U]),32);
            tracep->chgIData(oldp+524,(vlSelf->conv1__DOT__window_mul_result_2
                                       [1U][4U]),32);
            tracep->chgIData(oldp+525,(vlSelf->conv1__DOT__window_mul_result_2
                                       [2U][0U]),32);
            tracep->chgIData(oldp+526,(vlSelf->conv1__DOT__window_mul_result_2
                                       [2U][1U]),32);
            tracep->chgIData(oldp+527,(vlSelf->conv1__DOT__window_mul_result_2
                                       [2U][2U]),32);
            tracep->chgIData(oldp+528,(vlSelf->conv1__DOT__window_mul_result_2
                                       [2U][3U]),32);
            tracep->chgIData(oldp+529,(vlSelf->conv1__DOT__window_mul_result_2
                                       [2U][4U]),32);
            tracep->chgIData(oldp+530,(vlSelf->conv1__DOT__window_mul_result_2
                                       [3U][0U]),32);
            tracep->chgIData(oldp+531,(vlSelf->conv1__DOT__window_mul_result_2
                                       [3U][1U]),32);
            tracep->chgIData(oldp+532,(vlSelf->conv1__DOT__window_mul_result_2
                                       [3U][2U]),32);
            tracep->chgIData(oldp+533,(vlSelf->conv1__DOT__window_mul_result_2
                                       [3U][3U]),32);
            tracep->chgIData(oldp+534,(vlSelf->conv1__DOT__window_mul_result_2
                                       [3U][4U]),32);
            tracep->chgIData(oldp+535,(vlSelf->conv1__DOT__window_mul_result_2
                                       [4U][0U]),32);
            tracep->chgIData(oldp+536,(vlSelf->conv1__DOT__window_mul_result_2
                                       [4U][1U]),32);
            tracep->chgIData(oldp+537,(vlSelf->conv1__DOT__window_mul_result_2
                                       [4U][2U]),32);
            tracep->chgIData(oldp+538,(vlSelf->conv1__DOT__window_mul_result_2
                                       [4U][3U]),32);
            tracep->chgIData(oldp+539,(vlSelf->conv1__DOT__window_mul_result_2
                                       [4U][4U]),32);
            tracep->chgIData(oldp+540,(vlSelf->conv1__DOT__window_mul_result_3
                                       [0U][0U]),32);
            tracep->chgIData(oldp+541,(vlSelf->conv1__DOT__window_mul_result_3
                                       [0U][1U]),32);
            tracep->chgIData(oldp+542,(vlSelf->conv1__DOT__window_mul_result_3
                                       [0U][2U]),32);
            tracep->chgIData(oldp+543,(vlSelf->conv1__DOT__window_mul_result_3
                                       [0U][3U]),32);
            tracep->chgIData(oldp+544,(vlSelf->conv1__DOT__window_mul_result_3
                                       [0U][4U]),32);
            tracep->chgIData(oldp+545,(vlSelf->conv1__DOT__window_mul_result_3
                                       [1U][0U]),32);
            tracep->chgIData(oldp+546,(vlSelf->conv1__DOT__window_mul_result_3
                                       [1U][1U]),32);
            tracep->chgIData(oldp+547,(vlSelf->conv1__DOT__window_mul_result_3
                                       [1U][2U]),32);
            tracep->chgIData(oldp+548,(vlSelf->conv1__DOT__window_mul_result_3
                                       [1U][3U]),32);
            tracep->chgIData(oldp+549,(vlSelf->conv1__DOT__window_mul_result_3
                                       [1U][4U]),32);
            tracep->chgIData(oldp+550,(vlSelf->conv1__DOT__window_mul_result_3
                                       [2U][0U]),32);
            tracep->chgIData(oldp+551,(vlSelf->conv1__DOT__window_mul_result_3
                                       [2U][1U]),32);
            tracep->chgIData(oldp+552,(vlSelf->conv1__DOT__window_mul_result_3
                                       [2U][2U]),32);
            tracep->chgIData(oldp+553,(vlSelf->conv1__DOT__window_mul_result_3
                                       [2U][3U]),32);
            tracep->chgIData(oldp+554,(vlSelf->conv1__DOT__window_mul_result_3
                                       [2U][4U]),32);
            tracep->chgIData(oldp+555,(vlSelf->conv1__DOT__window_mul_result_3
                                       [3U][0U]),32);
            tracep->chgIData(oldp+556,(vlSelf->conv1__DOT__window_mul_result_3
                                       [3U][1U]),32);
            tracep->chgIData(oldp+557,(vlSelf->conv1__DOT__window_mul_result_3
                                       [3U][2U]),32);
            tracep->chgIData(oldp+558,(vlSelf->conv1__DOT__window_mul_result_3
                                       [3U][3U]),32);
            tracep->chgIData(oldp+559,(vlSelf->conv1__DOT__window_mul_result_3
                                       [3U][4U]),32);
            tracep->chgIData(oldp+560,(vlSelf->conv1__DOT__window_mul_result_3
                                       [4U][0U]),32);
            tracep->chgIData(oldp+561,(vlSelf->conv1__DOT__window_mul_result_3
                                       [4U][1U]),32);
            tracep->chgIData(oldp+562,(vlSelf->conv1__DOT__window_mul_result_3
                                       [4U][2U]),32);
            tracep->chgIData(oldp+563,(vlSelf->conv1__DOT__window_mul_result_3
                                       [4U][3U]),32);
            tracep->chgIData(oldp+564,(vlSelf->conv1__DOT__window_mul_result_3
                                       [4U][4U]),32);
            tracep->chgIData(oldp+565,(vlSelf->conv1__DOT__window_mul_result_4
                                       [0U][0U]),32);
            tracep->chgIData(oldp+566,(vlSelf->conv1__DOT__window_mul_result_4
                                       [0U][1U]),32);
            tracep->chgIData(oldp+567,(vlSelf->conv1__DOT__window_mul_result_4
                                       [0U][2U]),32);
            tracep->chgIData(oldp+568,(vlSelf->conv1__DOT__window_mul_result_4
                                       [0U][3U]),32);
            tracep->chgIData(oldp+569,(vlSelf->conv1__DOT__window_mul_result_4
                                       [0U][4U]),32);
            tracep->chgIData(oldp+570,(vlSelf->conv1__DOT__window_mul_result_4
                                       [1U][0U]),32);
            tracep->chgIData(oldp+571,(vlSelf->conv1__DOT__window_mul_result_4
                                       [1U][1U]),32);
            tracep->chgIData(oldp+572,(vlSelf->conv1__DOT__window_mul_result_4
                                       [1U][2U]),32);
            tracep->chgIData(oldp+573,(vlSelf->conv1__DOT__window_mul_result_4
                                       [1U][3U]),32);
            tracep->chgIData(oldp+574,(vlSelf->conv1__DOT__window_mul_result_4
                                       [1U][4U]),32);
            tracep->chgIData(oldp+575,(vlSelf->conv1__DOT__window_mul_result_4
                                       [2U][0U]),32);
            tracep->chgIData(oldp+576,(vlSelf->conv1__DOT__window_mul_result_4
                                       [2U][1U]),32);
            tracep->chgIData(oldp+577,(vlSelf->conv1__DOT__window_mul_result_4
                                       [2U][2U]),32);
            tracep->chgIData(oldp+578,(vlSelf->conv1__DOT__window_mul_result_4
                                       [2U][3U]),32);
            tracep->chgIData(oldp+579,(vlSelf->conv1__DOT__window_mul_result_4
                                       [2U][4U]),32);
            tracep->chgIData(oldp+580,(vlSelf->conv1__DOT__window_mul_result_4
                                       [3U][0U]),32);
            tracep->chgIData(oldp+581,(vlSelf->conv1__DOT__window_mul_result_4
                                       [3U][1U]),32);
            tracep->chgIData(oldp+582,(vlSelf->conv1__DOT__window_mul_result_4
                                       [3U][2U]),32);
            tracep->chgIData(oldp+583,(vlSelf->conv1__DOT__window_mul_result_4
                                       [3U][3U]),32);
            tracep->chgIData(oldp+584,(vlSelf->conv1__DOT__window_mul_result_4
                                       [3U][4U]),32);
            tracep->chgIData(oldp+585,(vlSelf->conv1__DOT__window_mul_result_4
                                       [4U][0U]),32);
            tracep->chgIData(oldp+586,(vlSelf->conv1__DOT__window_mul_result_4
                                       [4U][1U]),32);
            tracep->chgIData(oldp+587,(vlSelf->conv1__DOT__window_mul_result_4
                                       [4U][2U]),32);
            tracep->chgIData(oldp+588,(vlSelf->conv1__DOT__window_mul_result_4
                                       [4U][3U]),32);
            tracep->chgIData(oldp+589,(vlSelf->conv1__DOT__window_mul_result_4
                                       [4U][4U]),32);
            tracep->chgIData(oldp+590,(vlSelf->conv1__DOT__window_mul_result_5
                                       [0U][0U]),32);
            tracep->chgIData(oldp+591,(vlSelf->conv1__DOT__window_mul_result_5
                                       [0U][1U]),32);
            tracep->chgIData(oldp+592,(vlSelf->conv1__DOT__window_mul_result_5
                                       [0U][2U]),32);
            tracep->chgIData(oldp+593,(vlSelf->conv1__DOT__window_mul_result_5
                                       [0U][3U]),32);
            tracep->chgIData(oldp+594,(vlSelf->conv1__DOT__window_mul_result_5
                                       [0U][4U]),32);
            tracep->chgIData(oldp+595,(vlSelf->conv1__DOT__window_mul_result_5
                                       [1U][0U]),32);
            tracep->chgIData(oldp+596,(vlSelf->conv1__DOT__window_mul_result_5
                                       [1U][1U]),32);
            tracep->chgIData(oldp+597,(vlSelf->conv1__DOT__window_mul_result_5
                                       [1U][2U]),32);
            tracep->chgIData(oldp+598,(vlSelf->conv1__DOT__window_mul_result_5
                                       [1U][3U]),32);
            tracep->chgIData(oldp+599,(vlSelf->conv1__DOT__window_mul_result_5
                                       [1U][4U]),32);
            tracep->chgIData(oldp+600,(vlSelf->conv1__DOT__window_mul_result_5
                                       [2U][0U]),32);
            tracep->chgIData(oldp+601,(vlSelf->conv1__DOT__window_mul_result_5
                                       [2U][1U]),32);
            tracep->chgIData(oldp+602,(vlSelf->conv1__DOT__window_mul_result_5
                                       [2U][2U]),32);
            tracep->chgIData(oldp+603,(vlSelf->conv1__DOT__window_mul_result_5
                                       [2U][3U]),32);
            tracep->chgIData(oldp+604,(vlSelf->conv1__DOT__window_mul_result_5
                                       [2U][4U]),32);
            tracep->chgIData(oldp+605,(vlSelf->conv1__DOT__window_mul_result_5
                                       [3U][0U]),32);
            tracep->chgIData(oldp+606,(vlSelf->conv1__DOT__window_mul_result_5
                                       [3U][1U]),32);
            tracep->chgIData(oldp+607,(vlSelf->conv1__DOT__window_mul_result_5
                                       [3U][2U]),32);
            tracep->chgIData(oldp+608,(vlSelf->conv1__DOT__window_mul_result_5
                                       [3U][3U]),32);
            tracep->chgIData(oldp+609,(vlSelf->conv1__DOT__window_mul_result_5
                                       [3U][4U]),32);
            tracep->chgIData(oldp+610,(vlSelf->conv1__DOT__window_mul_result_5
                                       [4U][0U]),32);
            tracep->chgIData(oldp+611,(vlSelf->conv1__DOT__window_mul_result_5
                                       [4U][1U]),32);
            tracep->chgIData(oldp+612,(vlSelf->conv1__DOT__window_mul_result_5
                                       [4U][2U]),32);
            tracep->chgIData(oldp+613,(vlSelf->conv1__DOT__window_mul_result_5
                                       [4U][3U]),32);
            tracep->chgIData(oldp+614,(vlSelf->conv1__DOT__window_mul_result_5
                                       [4U][4U]),32);
            tracep->chgIData(oldp+615,(vlSelf->conv1__DOT__window_mul_result_6
                                       [0U][0U]),32);
            tracep->chgIData(oldp+616,(vlSelf->conv1__DOT__window_mul_result_6
                                       [0U][1U]),32);
            tracep->chgIData(oldp+617,(vlSelf->conv1__DOT__window_mul_result_6
                                       [0U][2U]),32);
            tracep->chgIData(oldp+618,(vlSelf->conv1__DOT__window_mul_result_6
                                       [0U][3U]),32);
            tracep->chgIData(oldp+619,(vlSelf->conv1__DOT__window_mul_result_6
                                       [0U][4U]),32);
            tracep->chgIData(oldp+620,(vlSelf->conv1__DOT__window_mul_result_6
                                       [1U][0U]),32);
            tracep->chgIData(oldp+621,(vlSelf->conv1__DOT__window_mul_result_6
                                       [1U][1U]),32);
            tracep->chgIData(oldp+622,(vlSelf->conv1__DOT__window_mul_result_6
                                       [1U][2U]),32);
            tracep->chgIData(oldp+623,(vlSelf->conv1__DOT__window_mul_result_6
                                       [1U][3U]),32);
            tracep->chgIData(oldp+624,(vlSelf->conv1__DOT__window_mul_result_6
                                       [1U][4U]),32);
            tracep->chgIData(oldp+625,(vlSelf->conv1__DOT__window_mul_result_6
                                       [2U][0U]),32);
            tracep->chgIData(oldp+626,(vlSelf->conv1__DOT__window_mul_result_6
                                       [2U][1U]),32);
            tracep->chgIData(oldp+627,(vlSelf->conv1__DOT__window_mul_result_6
                                       [2U][2U]),32);
            tracep->chgIData(oldp+628,(vlSelf->conv1__DOT__window_mul_result_6
                                       [2U][3U]),32);
            tracep->chgIData(oldp+629,(vlSelf->conv1__DOT__window_mul_result_6
                                       [2U][4U]),32);
            tracep->chgIData(oldp+630,(vlSelf->conv1__DOT__window_mul_result_6
                                       [3U][0U]),32);
            tracep->chgIData(oldp+631,(vlSelf->conv1__DOT__window_mul_result_6
                                       [3U][1U]),32);
            tracep->chgIData(oldp+632,(vlSelf->conv1__DOT__window_mul_result_6
                                       [3U][2U]),32);
            tracep->chgIData(oldp+633,(vlSelf->conv1__DOT__window_mul_result_6
                                       [3U][3U]),32);
            tracep->chgIData(oldp+634,(vlSelf->conv1__DOT__window_mul_result_6
                                       [3U][4U]),32);
            tracep->chgIData(oldp+635,(vlSelf->conv1__DOT__window_mul_result_6
                                       [4U][0U]),32);
            tracep->chgIData(oldp+636,(vlSelf->conv1__DOT__window_mul_result_6
                                       [4U][1U]),32);
            tracep->chgIData(oldp+637,(vlSelf->conv1__DOT__window_mul_result_6
                                       [4U][2U]),32);
            tracep->chgIData(oldp+638,(vlSelf->conv1__DOT__window_mul_result_6
                                       [4U][3U]),32);
            tracep->chgIData(oldp+639,(vlSelf->conv1__DOT__window_mul_result_6
                                       [4U][4U]),32);
            tracep->chgIData(oldp+640,(vlSelf->conv1__DOT__window_sum_1),32);
            tracep->chgIData(oldp+641,(vlSelf->conv1__DOT__window_sum_2),32);
            tracep->chgIData(oldp+642,(vlSelf->conv1__DOT__window_sum_3),32);
            tracep->chgIData(oldp+643,(vlSelf->conv1__DOT__window_sum_4),32);
            tracep->chgIData(oldp+644,(vlSelf->conv1__DOT__window_sum_5),32);
            tracep->chgIData(oldp+645,(vlSelf->conv1__DOT__window_sum_6),32);
            tracep->chgBit(oldp+646,(((4U <= (IData)(vlSelf->conv1__DOT__x_cnt)) 
                                      & (4U <= (IData)(vlSelf->conv1__DOT__y_cnt)))));
        }
        if (VL_UNLIKELY((vlSelf->__Vm_traceActivity
                         [3U] | vlSelf->__Vm_traceActivity
                         [4U]))) {
            tracep->chgCData(oldp+647,(vlSelf->conv1__DOT__window_in[0]),8);
            tracep->chgCData(oldp+648,(vlSelf->conv1__DOT__window_in[1]),8);
            tracep->chgCData(oldp+649,(vlSelf->conv1__DOT__window_in[2]),8);
            tracep->chgCData(oldp+650,(vlSelf->conv1__DOT__window_in[3]),8);
            tracep->chgCData(oldp+651,(vlSelf->conv1__DOT__window_in[4]),8);
            tracep->chgCData(oldp+652,(vlSelf->conv1__DOT__window_in
                                       [0U]),8);
            tracep->chgCData(oldp+653,(vlSelf->conv1__DOT__window_in
                                       [1U]),8);
            tracep->chgCData(oldp+654,(vlSelf->conv1__DOT__window_in
                                       [2U]),8);
            tracep->chgCData(oldp+655,(vlSelf->conv1__DOT__window_in
                                       [3U]),8);
            tracep->chgCData(oldp+656,(vlSelf->conv1__DOT__window_in
                                       [4U]),8);
        }
        tracep->chgBit(oldp+657,(vlSelf->clk));
        tracep->chgBit(oldp+658,(vlSelf->rst_n));
        tracep->chgCData(oldp+659,(vlSelf->cnn_data_in),8);
        tracep->chgBit(oldp+660,(vlSelf->cnn_data_in_valid));
        tracep->chgWData(oldp+661,(vlSelf->cnn_data_out),192);
        tracep->chgBit(oldp+667,(vlSelf->cnn_data_out_valid));
    }
}

void Vconv1___024root__traceCleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    Vconv1___024root* const __restrict vlSelf = static_cast<Vconv1___024root*>(voidSelf);
    Vconv1__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    {
        vlSymsp->__Vm_activity = false;
        vlSymsp->TOP.__Vm_traceActivity[0U] = 0U;
        vlSymsp->TOP.__Vm_traceActivity[1U] = 0U;
        vlSymsp->TOP.__Vm_traceActivity[2U] = 0U;
        vlSymsp->TOP.__Vm_traceActivity[3U] = 0U;
        vlSymsp->TOP.__Vm_traceActivity[4U] = 0U;
    }
}
